const panchangTerms = {
  en: {
    tithiCycle: [
      "Pratipada",
      "Dwitiya",
      "Tritiya",
      "Chaturthi",
      "Panchami",
      "Shashthi",
      "Saptami",
      "Ashtami",
      "Navami",
      "Dashami",
      "Ekadashi",
      "Dwadashi",
      "Trayodashi",
      "Chaturdashi",
      "Purnima",
      "Pratipada Krishna",
      "Dwitiya Krishna",
      "Tritiya Krishna",
      "Chaturthi Krishna",
      "Panchami Krishna",
      "Shashthi Krishna",
      "Saptami Krishna",
      "Ashtami Krishna",
      "Navami Krishna",
      "Dashami Krishna",
      "Ekadashi Krishna",
      "Dwadashi Krishna",
      "Trayodashi Krishna",
      "Chaturdashi Krishna",
      "Amavasya",
    ],
    nakshatraCycle: [
      "Ashwini",
      "Bharani",
      "Krittika",
      "Rohini",
      "Mrigashira",
      "Ardra",
      "Punarvasu",
      "Pushya",
      "Ashlesha",
      "Magha",
      "Purva Phalguni",
      "Uttara Phalguni",
      "Hasta",
      "Chitra",
      "Swati",
      "Vishakha",
      "Anuradha",
      "Jyeshtha",
      "Mula",
      "Purva Ashadha",
      "Uttara Ashadha",
      "Shravana",
      "Dhanishta",
      "Shatabhisha",
      "Purva Bhadrapada",
      "Uttara Bhadrapada",
      "Revati",
    ],
    yogas: ["Siddhi", "Shubha", "Saubhagya", "Dhriti", "Vriddhi", "Harshana", "Shiva"],
    karanas: ["Bava", "Balava", "Kaulava", "Taitila", "Garaja", "Vanija", "Vishti"],
    waxing: "Waxing energy",
    reflective: "Reflective energy",
    focusMap: {
      Love: "love",
      Career: "career",
      Health: "health",
      love: "love",
      career: "career",
      health: "health",
    },
    focusLabelMap: { love: "Love", career: "Career", health: "Health" },
    outlook: "Outlook",
    luckyColors: ["Gold", "Pearl White", "Indigo", "Rose", "Saffron"],
    luckyWindows: ["8:00 AM - 10:00 AM", "12:30 PM - 2:00 PM", "5:30 PM - 7:00 PM"],
    tones: [
      "A calm, well-timed action creates better results than urgency.",
      "The second half of the day feels more aligned for decisions.",
      "Trust steady effort over emotional pressure today.",
    ],
    messages: {
      Aries: {
        love: "Speak clearly instead of quickly. Emotional honesty works better than intensity today.",
        career: "A decisive move can help, but only after you review the details twice.",
        health: "Protect your energy from overcommitment and rushed routines.",
      },
      Taurus: {
        love: "Comfort and reassurance will say more than dramatic gestures today.",
        career: "Steady progress beats speed. Finish what is already in motion.",
        health: "Grounding rituals and a slower evening will help reset your mind.",
      },
      Gemini: {
        love: "A playful conversation can open a deeper emotional window.",
        career: "Networking and short-form communication are especially favorable.",
        health: "Balance mental stimulation with actual rest, not just distraction.",
      },
      Cancer: {
        love: "Nurturing energy feels natural, but keep your boundaries intact.",
        career: "Trust your instincts around timing, especially in people decisions.",
        health: "Hydration, sleep, and emotional decompression matter more than usual.",
      },
      Leo: {
        love: "Your warmth attracts attention, but real closeness needs listening too.",
        career: "Leadership stands out today when paired with humility and clarity.",
        health: "Channel restless fire into movement, not unnecessary stress.",
      },
      Virgo: {
        love: "Small thoughtful actions create stronger harmony than long explanations.",
        career: "Excellent day to improve systems, review plans, and refine execution.",
        health: "Reduce overthinking through structured breaks and lighter routines.",
      },
      Libra: {
        love: "Choose honesty over people-pleasing and the connection becomes easier.",
        career: "Collaborative work moves well when you set firmer expectations early.",
        health: "Restore balance with beauty, quiet, and a cleaner schedule.",
      },
      Scorpio: {
        love: "Let trust build slowly instead of testing people for certainty.",
        career: "Strong day for focused strategy, private planning, and long-term moves.",
        health: "Keep intensity productive by avoiding emotional bottling.",
      },
      Sagittarius: {
        love: "Lightness helps, but a direct answer may be needed today.",
        career: "Big-picture thinking is useful if paired with one concrete next step.",
        health: "Movement and sunlight support your mood and concentration.",
      },
      Capricorn: {
        love: "Reliability is attractive, but softness matters just as much now.",
        career: "Long-term planning and disciplined follow-through are strongly favored.",
        health: "Release physical tension from shoulders, neck, and jaw.",
      },
      Aquarius: {
        love: "Emotional distance can be misread, so say what you actually feel.",
        career: "Fresh ideas land well when translated into simple actions.",
        health: "Screen fatigue and irregular sleep need more attention today.",
      },
      Pisces: {
        love: "Intuition is strong, but confirmation still matters in close bonds.",
        career: "Creative thinking is high; give it structure so it becomes useful.",
        health: "Protect your energy from noise and overstimulation.",
      },
    },
  },
  hi: {
    tithiCycle: [
      "प्रतिपदा",
      "द्वितीया",
      "तृतीया",
      "चतुर्थी",
      "पंचमी",
      "षष्ठी",
      "सप्तमी",
      "अष्टमी",
      "नवमी",
      "दशमी",
      "एकादशी",
      "द्वादशी",
      "त्रयोदशी",
      "चतुर्दशी",
      "पूर्णिमा",
      "कृष्ण प्रतिपदा",
      "कृष्ण द्वितीया",
      "कृष्ण तृतीया",
      "कृष्ण चतुर्थी",
      "कृष्ण पंचमी",
      "कृष्ण षष्ठी",
      "कृष्ण सप्तमी",
      "कृष्ण अष्टमी",
      "कृष्ण नवमी",
      "कृष्ण दशमी",
      "कृष्ण एकादशी",
      "कृष्ण द्वादशी",
      "कृष्ण त्रयोदशी",
      "कृष्ण चतुर्दशी",
      "अमावस्या",
    ],
    nakshatraCycle: [
      "अश्विनी",
      "भरणी",
      "कृत्तिका",
      "रोहिणी",
      "मृगशिरा",
      "आर्द्रा",
      "पुनर्वसु",
      "पुष्य",
      "आश्लेषा",
      "मघा",
      "पूर्वा फाल्गुनी",
      "उत्तर फाल्गुनी",
      "हस्त",
      "चित्रा",
      "स्वाती",
      "विशाखा",
      "अनुराधा",
      "ज्येष्ठा",
      "मूल",
      "पूर्वाषाढ़ा",
      "उत्तराषाढ़ा",
      "श्रवण",
      "धनिष्ठा",
      "शतभिषा",
      "पूर्व भाद्रपद",
      "उत्तर भाद्रपद",
      "रेवती",
    ],
    yogas: ["सिद्धि", "शुभ", "सौभाग्य", "धृति", "वृद्धि", "हर्षण", "शिव"],
    karanas: ["बव", "बालव", "कौलव", "तैतिल", "गरज", "वणिज", "विष्टि"],
    waxing: "वृद्धि की ऊर्जा",
    reflective: "चिंतन की ऊर्जा",
    focusMap: {
      प्रेम: "love",
      करियर: "career",
      स्वास्थ्य: "health",
      love: "love",
      career: "career",
      health: "health",
    },
    focusLabelMap: { love: "प्रेम", career: "करियर", health: "स्वास्थ्य" },
    outlook: "मार्गदर्शन",
    luckyColors: ["स्वर्ण", "मोती सफेद", "इंडिगो", "गुलाबी", "केसरिया"],
    luckyWindows: ["सुबह 8:00 - 10:00", "दोपहर 12:30 - 2:00", "शाम 5:30 - 7:00"],
    tones: [
      "शांत और सही समय पर लिया गया कदम जल्दबाजी से बेहतर परिणाम देगा।",
      "दिन का दूसरा भाग निर्णयों के लिए अधिक अनुकूल रहेगा।",
      "आज भावनात्मक दबाव के बजाय स्थिर प्रयास पर भरोसा रखें।",
    ],
    messages: {
      Aries: {
        love: "जल्दी बोलने के बजाय स्पष्ट बोलें। भावनात्मक ईमानदारी अधिक लाभ देगी।",
        career: "निर्णायक कदम मदद कर सकता है, लेकिन पहले विवरण दोबारा जांचें।",
        health: "अत्यधिक व्यस्तता और भागदौड़ से अपनी ऊर्जा बचाएं।",
      },
      Taurus: {
        love: "नाटकीय इशारों से अधिक आश्वासन प्रभावी रहेगा।",
        career: "धीमी लेकिन स्थिर प्रगति अधिक लाभ देगी।",
        health: "शांत दिनचर्या और थोड़ा ठहराव मन को संतुलित करेगा।",
      },
      Gemini: {
        love: "हल्की-फुल्की बातचीत गहरी भावनात्मक निकटता ला सकती है।",
        career: "नेटवर्किंग और संवाद आज विशेष रूप से अनुकूल हैं।",
        health: "मानसिक सक्रियता के साथ वास्तविक विश्राम भी जरूरी है।",
      },
      Cancer: {
        love: "स्नेह स्वाभाविक रहेगा, लेकिन सीमाएं भी बनाए रखें।",
        career: "समय और लोगों से जुड़े निर्णयों में सहज ज्ञान उपयोगी होगा।",
        health: "जल, नींद और भावनात्मक शांति पर ध्यान दें।",
      },
      Leo: {
        love: "आकर्षण के साथ सुनना भी उतना ही जरूरी है।",
        career: "विनम्रता के साथ नेतृत्व अधिक प्रभावी रहेगा।",
        health: "बेचैनी को तनाव नहीं, गति में बदलें।",
      },
      Virgo: {
        love: "छोटे और विचारपूर्ण कार्य अधिक सामंजस्य लाएंगे।",
        career: "योजना, समीक्षा और व्यवस्था सुधारने का अच्छा समय है।",
        health: "अति-विश्लेषण को छोटे विरामों से कम करें।",
      },
      Libra: {
        love: "सबको खुश रखने के बजाय ईमानदारी अपनाएं।",
        career: "साझेदारी तब बेहतर चलेगी जब अपेक्षाएं पहले स्पष्ट हों।",
        health: "शांत वातावरण और संतुलित समयसारिणी उपयोगी रहेगी।",
      },
      Scorpio: {
        love: "विश्वास को धीरे-धीरे बढ़ने दें।",
        career: "रणनीति और दीर्घकालिक सोच के लिए अच्छा दिन है।",
        health: "भावनाओं को भीतर दबाने से बचें।",
      },
      Sagittarius: {
        love: "हल्कापन अच्छा है, पर आज स्पष्ट उत्तर भी जरूरी हो सकता है।",
        career: "बड़ी सोच के साथ एक ठोस कदम भी जोड़ें।",
        health: "गतिशीलता और धूप मन को सहारा देंगी।",
      },
      Capricorn: {
        love: "विश्वसनीयता के साथ कोमलता भी जरूरी है।",
        career: "अनुशासित और दीर्घकालिक योजना अनुकूल रहेगी।",
        health: "कंधों, गर्दन और जबड़े का तनाव कम करें।",
      },
      Aquarius: {
        love: "भावनाओं को स्पष्ट शब्द दें, दूरी गलत समझी जा सकती है।",
        career: "नए विचार तब सफल होंगे जब उन्हें सरल कार्रवाई में बदलें।",
        health: "स्क्रीन थकान और अनियमित नींद पर ध्यान दें।",
      },
      Pisces: {
        love: "अंतर्ज्ञान मजबूत है, फिर भी पुष्टि जरूरी है।",
        career: "रचनात्मकता को संरचना दें ताकि उसका लाभ मिले।",
        health: "शोर और अति-उत्तेजना से ऊर्जा बचाएं।",
      },
    },
  },
};

function daySeed(date = new Date()) {
  const utc = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.floor(utc / 86400000);
}

export function getLivePanchang(now = new Date(), lang = "en") {
  const seed = daySeed(now);
  const terms = panchangTerms[lang] ?? panchangTerms.en;
  const hours = now.getHours();
  const minutes = now.getMinutes().toString().padStart(2, "0");
  const locale = lang === "hi" ? "hi-IN" : "en-IN";

  return {
    dateLabel: now.toLocaleDateString(locale, {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    timeLabel: `${hours % 12 || 12}:${minutes} ${hours >= 12 ? "PM" : "AM"}`,
    tithi: terms.tithiCycle[seed % terms.tithiCycle.length],
    nakshatra: terms.nakshatraCycle[(seed + now.getMonth()) % terms.nakshatraCycle.length],
    yoga: terms.yogas[(seed + now.getDate()) % terms.yogas.length],
    karana: terms.karanas[(seed + hours) % terms.karanas.length],
    sunrise: lang === "hi" ? "सुबह 5:48" : "5:48 AM",
    sunset: lang === "hi" ? "शाम 6:31" : "6:31 PM",
    moonPhase: seed % 2 === 0 ? terms.waxing : terms.reflective,
  };
}

export function getRashiHoroscope(sign, focus = "love", lang = "en", now = new Date()) {
  const terms = panchangTerms[lang] ?? panchangTerms.en;
  const normalizedFocus = terms.focusMap[focus] ?? focus.toLowerCase();
  const base = terms.messages[sign] ?? terms.messages.Aries;
  const label = terms.focusLabelMap[normalizedFocus] ?? normalizedFocus;
  const tone = terms.tones[daySeed(now) % terms.tones.length];

  return {
    headline: `${sign} ${label} ${terms.outlook}`,
    body: `${base[normalizedFocus] ?? base.love} ${tone}`,
    luckyColor: terms.luckyColors[daySeed(now) % terms.luckyColors.length],
    luckyWindow: terms.luckyWindows[daySeed(now) % terms.luckyWindows.length],
  };
}
